### ISSUE TITLE
Ensure that lang-go cache dir doesn't grow unbounded

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph-go#20]
lang-go writes a cache to disk that is (in practice) a shared SSD on a node. lang-go needs to apply some eviction policy so that the cache doesn't grow unbounded.

see https://github.com/sourcegraph/sourcegraph/issues/627#issuecomment-461108211

**Comment by chrismwendt** [comment]
Sorry I didn't get to this sooner, hopping on it now.

**Comment by chrismwendt** [comment]
It looks like there's a file descriptor leak in go-langserver. Each time I trigger a new WebSocket connection, the zip archives get opened again and the output of `lsof +D /tmp/lang-go-archive-cache/` keeps growing.

I think this is happening because the archives for dependencies get combined into a single VFS, but their lifespan is not tied to the combined VFS in any way (probably should be refcounted).

**Comment by chrismwendt** [comment]
Fix pending https://github.com/sourcegraph/go-langserver/pull/359
